# Generated by Django 4.0.4 on 2022-06-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famila', '0002_alumno_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('Especialidad', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
